### ISSUE TITLE
Catch Invalid Token Exception and provide a better error message

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#11]
When you provide no or an invalid token, the application throws an exception. This should not be the case. I think we should provide a meaningful error message and exit the programm safely.

**Comment by nicosh** [comment]
if you want to assign me this issue i can work on this :)

**Comment by Fubinator** [comment]
Hey @nicosh i've assigned the issue to you. If you have any questions feel free to ask.
