### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#12]
We should provide a simple contributing guide to make it easier to work with the codebase for beginners.

**Comment by vidhi-mody** [comment]
Is this to be added in the README.md?

**Comment by Fubinator** [comment]
Since the dev environment is not too compllicated to setup, we could just put it at the end of the README.md. I leave it up to you if you put it into the README.md or create a CONTRIBUTING.md file and link it somewhere in the readme.
