### ISSUE TITLE
Add the bot's name to the .env file

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#15]
At the moment, the bot's name has to be `planning-poker-bot` for the application to work correctly. The user may want to have a different name for the bot so we should specify the bot's name in the `.env` file.

**Comment by alpceylan** [comment]
Can I take up this issue?

**Comment by Fubinator** [comment]
Hey @alpceylan of course. I've assigned you to the issue. If you have any questions feel free to ask.

**Comment by alpceylan** [comment]
Thank you, I'm starting.

**Comment by alpceylan** [comment]
I created a pull request. (https://github.com/Fubinator/planning-poker-discord-bot/pull/16)
