### ISSUE TITLE
Move source code into `src` directory

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#2]
The bot's source code should be in a designated `src` directory. For this, there should be an npm script in the `package.json` file and the README should be adjusted.

**Comment by erickborquez** [comment]
I'll be working on this.
After moving the sorce code to src changing the npm script dev to "cd src && nodemon index.js" and start to "cd src && node index.js" should be enough

**Comment by Fubinator** [comment]
Thanks @ErickJoestar 

I've assigned the Issue to you. It may be a good a idea to add nodemon as a dev-dependency as not everyone has it installed globally.
