### ISSUE TITLE
Let the user register for a game

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#21]
After starting a game initially there should be a !register command to register users for the new game. This is important to be able to run multiple games at once in the future. The poker object should get a list of players that have registered.

**Comment by milan090** [comment]
Can you provide more details on this. Should a user be allowed to join multiple games? Or a single game? And adding multi server support should be opened as a different issue and solved before this.

**Comment by Fubinator** [comment]
Since the user sends his estimate by direct message to the bot, I think it is easier if you only allow one game per user at a time. It also makes little sense to play several Planning Poker games at once, because you usually discuss the stories in a (virtual) meeting. 

I don't think we can implement this only after the multi server support. There is already #26 which should make it possible to play different games on multiple servers/channels.

The idea here is to ensure that only registered users can participate in the game. For this we can ignore the multi server support, i think.

**Comment by milan090** [comment]
@Fubinator Alright, then how should the user register? Typing !register might be bit annoying. How about doing it with a reaction?

**Comment by Fubinator** [comment]
I think you've got a point there. I actually like using a reaction. It should be made clear in the instructions, when the game is started, though.
