### ISSUE TITLE
!help command with detailed game instructions

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#22]
A `!help` command that displays game instructions (maybe with a link to some form of documentation) and the idea of playing planning poker in general could be useful for inexperienced users.

**Comment by jooaodanieel** [comment]
Hi @Fubinator can I take this issue? Thanks in advance

**Comment by Fubinator** [comment]
Of course @jooaodanieel, go ahead! If you have any quuestions feel free to ask.
