### ISSUE TITLE
Instructions how to setup a bot in the Discord Developer Portal

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#23]
Since it's non-trivial to create a Discord bot in the Discord Developer Portal, we should provide a guide in the README.

Reference: https://discordpy.readthedocs.io/en/latest/discord.html

**Comment by ShahzaibJutt** [comment]
I want to work on this.

**Comment by Fubinator** [comment]
Hey @ShahzaibJutt. Go for it! I've assigned you to the issue. If you have any questions feel free to ask.

**Comment by ShahzaibJutt** [comment]
Should I also include pictures in the guide or I just create steps for creating the bot and after which section in the `readme.md` I place this guide. Sorry for delay I am waiting for hactoberfest to start.

**Comment by Fubinator** [comment]
No worries! Just place it between the installation and configuration section.  I dont think that Images are necessary. In addition to that, the readme would be quite bloated with those images i guess. You could provide a link to the reference If you want to.

**Comment by ShahzaibJutt** [comment]
Oh sorry I don't read your comment and create the PR. It is after the Getting started in the readme.

**Comment by Fubinator** [comment]
For reference: @milan090 created a discord bot himself with really good instructions:

https://github.com/milan090/simple-discord-music-bot
https://github.com/milan090/simple-discord-music-bot/blob/master/CREATE_BOT.md

Maybe you can get inspired by it.

**Comment by xxKeefer** [comment]
hey guys, i am about to try and help out with #3 and i wanted to get the bot running on my local in a priovate discord just to have a play, does it require any scopes other than bot? and what perms should it be given?

# edit
sorry i just read the changes to the PR for this issue suggested by rgroves, found the invite link there

**Comment by Fubinator** [comment]
Hey @xxKeefer I don't know if @ShahzaibJutt is updating his changes any  time soon. I've seen multiple people struggle with setting up the bot. If you want to, you could take on this issue as well. I have seen that you are a native speaker, so I would be very grateful if you or someone else who is a native speaker could take over.

**Comment by ShahzaibJutt** [comment]
Sorry @Fubinator my internet was off for a while. Can you please tell me what to improve?

**Comment by Fubinator** [comment]
No worries @ShahzaibJutt  just have a look at your PR. Someone commented and refer to this comment: https://github.com/Fubinator/planning-poker-discord-bot/issues/23#issuecomment-702308117
