### ISSUE TITLE
Make sure the provided story points are a number.

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#25]
Currently the user is able to provide any string as the amount of story points for a question. I think we should make sure it is a) a number and b) cast the number provided as a string to a number since we make calculations with the total amount of story points. If the user did not provide a valid number, a message that indicates that the amount should be a  valid number should be sent.

**Comment by aknrg77** [comment]
I would like to fix this issue

**Comment by Fubinator** [comment]
@aknrg77 sure! I've assigned the issue to you. Feel free to ask if you have any questions.
