### ISSUE TITLE
Provide one Poker Object for each channel

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#26]
Currently it is possible to start a game in two or more channels, but the actual Game is shared across those channels. Because of that, it is possible to ask questions in one channel and provide the story points in the other one. This is because all games share one `Poker` Object. Each game should have its own designated object for this to work properly.

**Comment by Rocksheep** [comment]
Do you mind if I pick this one up?

**Comment by Fubinator** [comment]
Not at all, go ahead!  I've assigned the issue to you. If you have any questions feel free to ask!
