### ISSUE TITLE
Better game instructions in README

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#3]
The game instructions in the README should be revised to make them easier to understand.

**Comment by ackr-8** [comment]
hey there, i can help you

**Comment by Fubinator** [comment]
hey @ackr-8, feel free to submit a PR. If you have any questions feel free to ask.

**Comment by xxKeefer** [comment]
hey there @Fubinator, I would like to help out. i can see the instructions are pretty sparse right now. Are we assuming the users already know planning poker? Would you like me to outline how to play planning poker in a live setting first then give more detailed instructions for the bot commands or just stick to the bot commands?

**Comment by Fubinator** [comment]
Implemented with #44
