### ISSUE TITLE
Test Setup

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#34]
As the bot is growing quite fast I think it is a good idea to add tests. We need a test setup and if possible a github action to run the tests automatically. I don't think it is necessary to reach 100% test coverage in this step, but we need a starting point.

**Comment by leonardxfce** [comment]
I can take a look of this!

**Comment by Fubinator** [comment]
Sure, go ahead @leonardxfce. I've assigned the issue to you. If you have any questions feel free to ask.

**Comment by leonardxfce** [comment]
I created my first PR! 🎉
