### ISSUE TITLE
Use Discord Command files instead of if/else

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#35]
The Discord.js docs deprecate huge if/else statements for bot commands:
https://discordjs.guide/creating-your-bot/adding-more-commands.html#the-problem-with-if-else-if

I agree that the commands are quite confusing, so we should use the recommend Command  Handling with individual command files:
https://discordjs.guide/command-handling/#individual-command-files

**Comment by yerlantemir** [comment]
Hi, assign it to me. And I think you should edit issue title, in this case we are not going to use discord commands but discord command files

**Comment by Fubinator** [comment]
Hey @yerlantemir I've assigned it to you!

**Comment by yerlantemir** [comment]
done @Fubinator
