### ISSUE TITLE
Better bot messages

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#4]
The bot messages should be updated as they are sometimes difficult to understand.

**Comment by rgroves** [comment]
I can pick this one up if it's still unassigned.

Could anyone help on getting this to run in Discord to test changes?

I have already created an app on the Discord Developer Portal and have a Bot Token for the .env file. Then what? Sorry, have never developed or worked on a Discord bot before this. Thanks!

Edit: Disregard about the help I believe I have it sorted and mentioned steps I took in #27 in hopes that can be added for future contributors who may have never worked with a Discord bot.

**Comment by Fubinator** [comment]
Hey @rgroves I've assigned the issue to you. Did you manage to set up a bot? If not I could give you a quick explaination.

**Comment by rgroves** [comment]
Thanks @Fubinator, I was able to get the bot set up. I was just missing the step where you have to use that URL to be able to enable it for a Discord server. I'm working on the issue now.
