### ISSUE TITLE
Log to console when a game was started

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#46]
When a game is started, a meaningful message (preferably with the server/channel name) should be written to the console.

**Comment by sambatlim** [comment]
I want to work on this issue. Could you assign me for this?

**Comment by Fubinator** [comment]
Sure @sambatlim  go ahead! If you have any questions feel free to ask.

**Comment by sambatlim** [comment]
> Sure @sambatlim go ahead! If you have any questions feel free to ask.

I stuck with adding the bot to the server.

**Comment by Fubinator** [comment]
@sambatlim Have a look over here under "inviting the bot": https://github.com/milan090/simple-discord-music-bot/blob/master/CREATE_BOT.md

**Comment by sambatlim** [comment]
> @sambatlim Have a look over here under "inviting the bot": https://github.com/milan090/simple-discord-music-bot/blob/master/CREATE_BOT.md

Thanks, I got it now.

**Comment by sambatlim** [comment]
When user type !start, in the console.log() should print out the channel name.
Am I right?

**Comment by Fubinator** [comment]
Yes @sambatlim

**Comment by sambatlim** [comment]
> Yes @sambatlim

I have made the pull request.
