### ISSUE TITLE
ASCII Art when starting the bot

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#47]
Let's have some fun: When starting the bot, let's display something with ASCII Art in the console. "Planning Poker Discord Bot" may be a little bit too long for this, so we should either display "PPDB" or "Planning Poker Bot" or something else.

There might be a library for this, I don't really know. If you do not want to use a library for this you can just use this generator: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20

**Comment by ryzbaka** [comment]
I'm interested in implementing this feature.

**Comment by Fubinator** [comment]
Sure, go ahead @ryzbaka. I've assigned you to the issue.

**Comment by ryzbaka** [comment]
Done.
https://github.com/Fubinator/planning-poker-discord-bot/pull/52
