### ISSUE TITLE
Add some aliases to the commands

### ISSUE THREAD

**Issue by xxKeefer** [Fubinator/planning-poker-discord-bot#49]
I'm in the process of doing some manual testing right now and typing `!storypoints` multiple times is annoying. maybe something like `!sp` and some other aliases for the other commands?

**Comment by Fubinator** [comment]
I think the idea itself is good. One thought that came to my mind is that we have to be careful that our commands don't overlap with the commands of other bots. We cannot completely prevent this, but we should use meaningful commands that are as unique as possible. With that in mind aliases can be implemented.

**Comment by JStruk** [comment]
I'd love to help out with this issue/feature! Could you assign it to me? Also, besides !sp for !storypoints, any other preferred aliases for the commands? Thanks!

**Comment by Fubinator** [comment]
Hey @JStruk. We already have an alias for !storypoints with #53. You can add some more. Just look at the available commands and use some kind of abbreviations (2-3 characters).

**Comment by JStruk** [comment]
@Fubinator cool, thanks. Would you prefer I stick to the switch/case with strings of the command/alias, or refactor the code to implement the command aliases built into discord js? (https://discordjs.guide/command-handling/adding-features.html#command-aliases)

**Comment by Fubinator** [comment]
@JStruk I did not know there were such kind of aliases, so I think it's a good idea to use those aliases. :+1:

**Comment by JStruk** [comment]
@Fubinator 👍  I'll have a PR up shortly.
