### ISSUE TITLE
Welcome message in the console

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#6]
When the bot is started, it currently logs "I'm ready" when it is connected to Discord. 

I imagine a welcome message and maybe some information, like version number, when the bot is started and a more detailed message when the bot is connected to Discord.

**Comment by dawksh** [comment]
I'd like to take this up, can you assign it to me?

**Comment by Fubinator** [comment]
@DevDaksh you're assigned. If you have any questions feel free to ask.
