### ISSUE TITLE
Add hacktoberfest label

### ISSUE THREAD

**Issue by bsantosh909** [Fubinator/planning-poker-discord-bot#61]
Hacktoberfest just updated their terms, so it would be good if you could add hacktoberfest label to the repository topic so that all the PR's submitted are eligible for the event.

**Comment by bsantosh909** [comment]
It seems you can even accept the individual PR by adding the **hacktoberfest-accepted** label

**Comment by Fubinator** [comment]
Thank you, I just added the label.
