### ISSUE TITLE
.env.example file not present

### ISSUE THREAD

**Issue by MaxWinsemius** [Fubinator/planning-poker-discord-bot#68]
The readme notes to copy the `.env.example` file to the `.env` file, but the example file is not present in the repository. It does not seem to matter too much as it is only used for the later given variable, but it would be nice for completeness to have the file in the repository.

**Comment by Fubinator** [comment]
You're right. The `.env.example` file should be (re)added. I don't really have time at the moment to work on this repo, so I'd be happy if you or someone else would work on this.

**Comment by tadeuif** [comment]
Same issue here. No .env.examplo file present. Can someone uploaded it?

**Comment by Fubinator** [comment]
Hey @tadeuif this should be the the content of the `.env.example` file:
```env
DISCORD_SECRET="YOUR_DISCORD_SECRET"
```
I might work on fixing the bot in the near future. But feel free to submit a PR with the file.
