### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#7]
We should lint the codebase to provide a common code style.

**Comment by naomi-lgbt** [comment]
Hello~!

I can set up a linter if you'd like. I can configure ESLint to check for errors, and I can add a CI to test PRs for linting issues.

**Comment by Fubinator** [comment]
Hi @nhcarrigan, sounds good! I'll assign you to the Issue. If you have any questions feel free to ask.
