### ISSUE TITLE
Flag to determine that game is running

### ISSUE THREAD

**Issue by Fubinator** [Fubinator/planning-poker-discord-bot#9]
The "!start" command currently has no functionality besides the game instructions. Here should a flag be set indicating that the game has been started.  Furthermore it should only be possible to ask a question, assign story points and end the game if this flag is set to true.
When you end the game, the flag should be set to false again.

**Comment by aknrg77** [comment]
I would like to give it a shot

**Comment by Fubinator** [comment]
Sure, go ahead! I've assigned the issue to you.

**Comment by Fubinator** [comment]
This is not necessary anymore, because we delete the game after it ends anyways.
